name: Tests
on: push
jobs:
  examples:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: cross-contract-call
        run: cd examples/cross-contract-call && yarn && yarn build && yarn test && rm -rf node_modules && rm -rf build && cd ../..
      - name: fungible-token
        run: cd examples/fungible-token && yarn && yarn build && yarn test && rm -rf node_modules && rm -rf build && cd ../..
      - name: lockable-fungible-token
        run: cd examples/lockable-fungible-token && yarn && yarn build && yarn test && rm -rf node_modules && rm -rf build && cd ../..
      - name: non-fungible-token
        run: cd examples/non-fungible-token && yarn && yarn build && yarn test && rm -rf node_modules && rm -rf build && cd ../..
      - name: status-message
        run: cd examples/status-message && yarn && yarn build && yarn test && rm -rf node_modules && rm -rf build && cd ../..
      - name: clean-state
        run: cd examples/clean-state && yarn && yarn build && yarn test && rm -rf node_modules && rm -rf build && cd ../..
      - name: template
        run: cd examples/template && yarn && yarn build && yarn test && rm -rf node_modules && rm -rf build && cd ../..